GET http://localhost:3000/piedras HTTP/1.1

POST http://localhost:3000/piedras HTTP/1.1
content-type: application/json

{
    "descripcion": "Prueba piedras",
    "costo": 4515454,
    "venta": 78787 
}





